# utils/salesperson_performance/notification/email_builder.py
"""
HTML Email Builder for Salesperson Performance Alerts.

Converts the warning bulletin (generated by warning_bulletin.py) into
a professional, responsive HTML email.

Phase 1: Team-level bulletin (same content as UI).
Phase 2 (future): Per-salesperson with individual KPIs.

Usage:
    from utils.salesperson_performance.notification.email_builder import (
        build_bulletin_email,
    )

    subject, html = build_bulletin_email(
        bulletin=warning_bulletin,
        active_filters=active_filters,
        overview_metrics=overview_metrics,
        sender_name="Quy Ngo",
    )

VERSION: 2.0.0 — Added build_warning_email(), build_warning_plain_text()
"""

import logging
from datetime import date, datetime
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


# =============================================================================
# CSS (inline — email clients strip <style> blocks)
# =============================================================================

_STYLES = {
    "container": (
        "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, "
        "Helvetica, Arial, sans-serif; max-width: 960px; margin: 0 auto; "
        "background: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; "
        "overflow: hidden;"
    ),
    "header": (
        "background: linear-gradient(135deg, #1f77b4, #2ca02c); color: #ffffff; "
        "padding: 24px 32px; font-size: 14px;"
    ),
    "header_title": "margin: 0 0 4px 0; font-size: 22px; font-weight: 700;",
    "header_sub": "margin: 0; font-size: 13px; opacity: 0.9;",
    "body": "padding: 24px 32px;",
    "headline": (
        "background: #f8f9fa; border-left: 4px solid #1f77b4; "
        "padding: 12px 16px; margin: 0 0 20px 0; font-size: 14px; "
        "color: #333; border-radius: 0 4px 4px 0; line-height: 1.5;"
    ),
    "section_title": (
        "font-size: 15px; font-weight: 600; margin: 20px 0 8px 0; "
        "color: #333;"
    ),
    # Severity boxes
    "box_high": (
        "background: #fef2f2; border-left: 4px solid #dc3545; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_medium": (
        "background: #fffbeb; border-left: 4px solid #f59e0b; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_low": (
        "background: #eff6ff; border-left: 4px solid #3b82f6; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_ok": (
        "background: #f0fdf4; border-left: 4px solid #22c55e; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "alert_item": "margin: 6px 0; font-size: 14px; color: #333; line-height: 1.5;",
    "footer": (
        "background: #f8f9fa; padding: 16px 32px; font-size: 11px; "
        "color: #888; border-top: 1px solid #e0e0e0;"
    ),
    "btn": (
        "display: inline-block; padding: 10px 24px; background: #1f77b4; "
        "color: #ffffff; text-decoration: none; border-radius: 4px; "
        "font-size: 14px; font-weight: 600;"
    ),
    "btn_secondary": (
        "display: inline-block; padding: 6px 14px; background: #f0f0f0; "
        "color: #333; text-decoration: none; border-radius: 4px; "
        "font-size: 12px; font-weight: 500; border: 1px solid #ddd;"
    ),
    "inline_link": (
        "color: #1f77b4; text-decoration: none; font-weight: 600; font-size: 12px;"
    ),
    "muted": "color: #999; font-size: 12px;",
}


# =============================================================================
# PUBLIC API
# =============================================================================

def build_bulletin_email(
    bulletin: Dict,
    active_filters: Dict,
    overview_metrics: Optional[Dict] = None,
    sender_name: str = "Prostech BI",
    dashboard_url: str = "",
    cc_note: str = "",
) -> tuple:
    """
    Build HTML email from warning bulletin data.

    Args:
        bulletin:         Output of generate_warning_bulletin()
        active_filters:   Current filter state (period, year, dates)
        overview_metrics: Overview metrics dict (optional — for KPI snapshot)
        sender_name:      Name of the person triggering the email
        dashboard_url:    Link to dashboard (from APP_BASE_URL)
        cc_note:          Note for CC recipients (e.g., "Sent to your direct report X")

    Returns:
        Tuple of (subject: str, html_body: str)
    """
    period_label = bulletin.get("period_label", "")
    headline = bulletin.get("headline", "")
    alerts = bulletin.get("alerts", [])
    alert_count = bulletin.get("alert_count", 0)
    has_critical = bulletin.get("has_critical", False)

    # Subject line
    if has_critical:
        subject = f"🚨 Sales Alert — {alert_count} issue(s) — {period_label}"
    elif alert_count > 0:
        subject = f"⚡ Sales Bulletin — {alert_count} item(s) — {period_label}"
    else:
        subject = f"✅ Sales Bulletin — All Clear — {period_label}"

    # Build HTML
    html_parts = []

    # --- Header ---
    html_parts.append(f"""
    <div style="{_STYLES['container']}">
        <div style="{_STYLES['header']}">
            <h1 style="{_STYLES['header_title']}">⚡ Sales Performance Bulletin</h1>
            <p style="{_STYLES['header_sub']}">{period_label} &nbsp;|&nbsp; Generated {datetime.now().strftime('%d %b %Y, %H:%M')}</p>
        </div>
        <div style="{_STYLES['body']}">
    """)

    # --- CC Note (for managers) ---
    if cc_note:
        html_parts.append(f"""
            <p style="font-size: 12px; color: #666; font-style: italic; margin: 0 0 16px 0;">
                {_esc(cc_note)}
            </p>
        """)

    # --- Headline ---
    html_parts.append(f"""
        <div style="{_STYLES['headline']}">
            <strong>📊 Snapshot:</strong> {_esc(headline)}
        </div>
    """)

    # --- KPI Snapshot (optional) ---
    if overview_metrics:
        html_parts.append(_build_kpi_snapshot(overview_metrics))

    # --- Alerts ---
    # Build page URL for deep links within alerts
    _page_url = f"{dashboard_url.rstrip('/')}/Salesperson_Performance" if dashboard_url else ""

    if alerts:
        sorted_alerts = sorted(
            alerts,
            key=lambda a: {"high": 0, "medium": 1, "low": 2}.get(a["severity"], 9),
        )
        high = [a for a in sorted_alerts if a["severity"] == "high"]
        medium = [a for a in sorted_alerts if a["severity"] == "medium"]
        low = [a for a in sorted_alerts if a["severity"] == "low"]

        if high:
            html_parts.append(_build_alert_section(
                title="🚨 Action Required",
                alerts=high,
                box_style=_STYLES["box_high"],
                page_url=_page_url,
            ))

        if medium:
            html_parts.append(_build_alert_section(
                title="⚠️ Monitor",
                alerts=medium,
                box_style=_STYLES["box_medium"],
                page_url=_page_url,
            ))

        if low:
            html_parts.append(_build_alert_section(
                title="ℹ️ For Your Awareness",
                alerts=low,
                box_style=_STYLES["box_low"],
                page_url=_page_url,
            ))
    else:
        html_parts.append(f"""
            <div style="{_STYLES['box_ok']}">
                <p style="{_STYLES['alert_item']}">
                    ✅ <strong>No issues detected</strong> — all metrics within normal range.
                </p>
            </div>
        """)

    # --- CTA Buttons — Deep Links to Dashboard Tabs ---
    if dashboard_url:
        page_url = f"{dashboard_url.rstrip('/')}/Salesperson_Performance"
        html_parts.append(f"""
            <div style="text-align: center; margin: 24px 0 12px 0;">
                <a href="{_esc(page_url)}" style="{_STYLES['btn']}">
                    📊 Open Dashboard
                </a>
            </div>
            <div style="text-align: center; margin: 0 0 8px 0;">
                <a href="{_esc(page_url)}" style="{_STYLES['btn_secondary']}; margin: 0 4px;">📦 Backlog</a>
                <a href="{_esc(page_url)}" style="{_STYLES['btn_secondary']}; margin: 0 4px;">💰 Payment</a>
                <a href="{_esc(page_url)}" style="{_STYLES['btn_secondary']}; margin: 0 4px;">🎯 KPI &amp; Targets</a>
                <a href="{_esc(page_url)}" style="{_STYLES['btn_secondary']}; margin: 0 4px;">📋 Sales Detail</a>
            </div>
            <p style="text-align: center; {_STYLES['muted']}; margin: 4px 0 0 0;">
                Login required — you'll be redirected to the dashboard after sign-in
            </p>
        """)

    # --- Close body ---
    html_parts.append("</div>")

    # --- Footer ---
    html_parts.append(f"""
        <div style="{_STYLES['footer']}">
            <p style="margin: 0 0 4px 0;">
                Auto-generated by <strong>Prostech BI Dashboard</strong>
                {f'&nbsp;|&nbsp; Triggered by {_esc(sender_name)}' if sender_name != 'Prostech BI' else ''}
            </p>
            <p style="margin: 0 0 4px 0;">
                Links above require login — if not signed in, you'll be prompted to log in first.
            </p>
            <p style="margin: 0;">
                To manage notifications: Dashboard → 📧 Notifications tab
            </p>
        </div>
    </div>
    """)

    html_body = "\n".join(html_parts)
    return subject, html_body


def build_bulletin_plain_text(bulletin: Dict) -> str:
    """
    Build plain text fallback from bulletin.

    Simple text version for email clients that don't render HTML.
    """
    lines = [
        f"Sales Performance Bulletin — {bulletin.get('period_label', '')}",
        "",
        f"Snapshot: {bulletin.get('headline', '')}",
        "",
    ]

    alerts = bulletin.get("alerts", [])
    if alerts:
        for a in alerts:
            severity_map = {"high": "🔴", "medium": "🟡", "low": "🔵"}
            icon = severity_map.get(a["severity"], "•")
            lines.append(f"  {icon} {a['message']}")
    else:
        lines.append("  ✅ No issues detected.")

    lines.extend([
        "",
        "—",
        "Auto-generated by Prostech BI Dashboard",
    ])

    return "\n".join(lines)


# =============================================================================
# INTERNAL HELPERS
# =============================================================================

def _esc(text: str) -> str:
    """Escape HTML entities."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _fmt(value: float) -> str:
    """Format currency: $1.2M / $850K / $1,234"""
    if abs(value) >= 1_000_000:
        return f"${value / 1_000_000:,.1f}M"
    elif abs(value) >= 10_000:
        return f"${value / 1_000:,.0f}K"
    else:
        return f"${value:,.0f}"


def _build_kpi_snapshot(metrics: Dict) -> str:
    """Build KPI summary table from overview_metrics."""
    revenue = metrics.get("total_revenue", 0)
    gp = metrics.get("total_gp", 0)
    gp_pct = metrics.get("gp_percent", 0)
    gp1 = metrics.get("total_gp1", 0)
    invoices = metrics.get("total_invoices", 0)
    customers = metrics.get("total_customers", 0)

    row_style = "padding: 8px 14px; font-size: 14px; border-bottom: 1px solid #eee;"
    label_style = f"{row_style} color: #666; width: 130px;"
    value_style = f"{row_style} font-weight: 600; color: #333;"

    return f"""
    <table style="width: 100%; border-collapse: collapse; margin: 0 0 16px 0;">
        <tr>
            <td style="{label_style}">💰 Revenue</td>
            <td style="{value_style}">{_fmt(revenue)}</td>
            <td style="{label_style}">📈 GP</td>
            <td style="{value_style}">{_fmt(gp)} ({gp_pct:.1f}%)</td>
        </tr>
        <tr>
            <td style="{label_style}">📊 GP1</td>
            <td style="{value_style}">{_fmt(gp1)}</td>
            <td style="{label_style}">📋 Invoices</td>
            <td style="{value_style}">{invoices:,}</td>
        </tr>
    </table>
    """


def _build_alert_section(
    title: str,
    alerts: List[Dict],
    box_style: str,
    page_url: str = "",
) -> str:
    """Build one alert severity section with contextual deep links."""
    items = []
    for a in alerts:
        msg = _esc(a["message"])
        icon = a.get("icon", "•")
        link = _get_contextual_link(a["message"], page_url)
        link_html = f' <a href="{_esc(link)}" style="{_STYLES["inline_link"]}">View →</a>' if link else ""
        items.append(
            f'<p style="{_STYLES["alert_item"]}">{icon} {msg}{link_html}</p>'
        )
    items_html = "\n".join(items)

    return f"""
        <p style="{_STYLES['section_title']}">{title}</p>
        <div style="{box_style}">
            {items_html}
        </div>
    """


# Keyword → tab label mapping for deep links
_ALERT_TAB_HINTS = [
    # (keywords in alert message, tab label for hint)
    (["past etd", "delivery", "backlog", "orders past", "ship"], "Backlog"),
    (["overdue", "outstanding", "ar ", "90+", "aging", "payment"], "Payment"),
    (["kpi", "achievement", "target", "behind"], "KPI & Targets"),
    (["customer", "decline", "inactive", "concentration"], "Sales Detail"),
]


def _get_contextual_link(message: str, page_url: str) -> str:
    """Return page_url if message matches a tab keyword, else empty string."""
    if not page_url:
        return ""
    msg_lower = message.lower()
    for keywords, _tab in _ALERT_TAB_HINTS:
        if any(kw in msg_lower for kw in keywords):
            return page_url
    return ""


# =============================================================================
# WARNING EMAIL BUILDER (v3.0 — bilingual + categorized)
# =============================================================================

_WARNING_STYLES = {
    "container": (
        "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, "
        "Helvetica, Arial, sans-serif; max-width: 960px; margin: 0 auto; "
        "background: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; "
        "overflow: hidden;"
    ),
    "header": (
        "background: linear-gradient(135deg, #b91c1c, #dc2626); color: #ffffff; "
        "padding: 24px 32px; font-size: 14px;"
    ),
    "header_title": "margin: 0 0 4px 0; font-size: 22px; font-weight: 700;",
    "header_sub": "margin: 0; font-size: 13px; opacity: 0.9;",
    "body": "padding: 24px 32px;",
    "section_title": (
        "font-size: 15px; font-weight: 600; margin: 24px 0 10px 0; "
        "color: #333; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px;"
    ),
    "table": (
        "width: 100%; border-collapse: collapse; margin: 0 0 16px 0; "
        "font-size: 13px;"
    ),
    "th": (
        "background: #f1f5f9; padding: 8px 12px; text-align: left; "
        "font-weight: 600; color: #475569; border-bottom: 2px solid #e2e8f0; "
        "font-size: 12px;"
    ),
    "td": "padding: 8px 12px; border-bottom: 1px solid #f1f5f9; color: #333;",
    "td_amount": (
        "padding: 8px 12px; border-bottom: 1px solid #f1f5f9; color: #333; "
        "text-align: right; font-weight: 600; font-family: monospace;"
    ),
    "consequences_box": (
        "background: #fef2f2; border: 2px solid #dc2626; border-radius: 8px; "
        "padding: 20px 24px; margin: 24px 0;"
    ),
    "consequences_title": (
        "margin: 0 0 12px 0; font-size: 16px; font-weight: 700; color: #991b1b;"
    ),
    "consequences_item": (
        "margin: 8px 0; font-size: 14px; color: #7f1d1d; line-height: 1.5;"
    ),
    "customer_box": (
        "background: #fff7ed; border-left: 4px solid #ea580c; "
        "padding: 12px 16px; margin: 0 0 10px 0; border-radius: 0 6px 6px 0;"
    ),
    "customer_critical": (
        "background: #fef2f2; border-left: 4px solid #dc2626; "
        "padding: 12px 16px; margin: 0 0 10px 0; border-radius: 0 6px 6px 0;"
    ),
    "invoice_list": "font-size: 12px; color: #666; margin: 4px 0 0 20px;",
    "alert_box": (
        "background: #f8f9fa; border-left: 4px solid #6b7280; "
        "padding: 10px 16px; margin: 0 0 8px 0; border-radius: 0 4px 4px 0;"
    ),
    "alert_box_backlog": (
        "background: #fef3c7; border-left: 4px solid #d97706; "
        "padding: 10px 16px; margin: 0 0 8px 0; border-radius: 0 4px 4px 0;"
    ),
    "alert_box_kpi": (
        "background: #ede9fe; border-left: 4px solid #7c3aed; "
        "padding: 10px 16px; margin: 0 0 8px 0; border-radius: 0 4px 4px 0;"
    ),
    "alert_box_payment": (
        "background: #eff6ff; border-left: 4px solid #3b82f6; "
        "padding: 10px 16px; margin: 0 0 8px 0; border-radius: 0 4px 4px 0;"
    ),
    "footer": (
        "background: #f8f9fa; padding: 16px 32px; font-size: 11px; "
        "color: #888; border-top: 1px solid #e0e0e0;"
    ),
    "btn_primary": (
        "display: inline-block; padding: 10px 24px; background: #dc2626; "
        "color: #ffffff; text-decoration: none; border-radius: 4px; "
        "font-size: 14px; font-weight: 600;"
    ),
    "btn_secondary": (
        "display: inline-block; padding: 6px 14px; background: #f0f0f0; "
        "color: #333; text-decoration: none; border-radius: 4px; "
        "font-size: 12px; font-weight: 500; border: 1px solid #ddd;"
    ),
}


# =============================================================================
# BILINGUAL TEXTS
# =============================================================================

DEFAULT_DEADLINE_DAYS = 7

_TEXTS = {
    'en': {
        # Header
        'warning_title': '⚠️ Sales Performance Warning — Action Required',
        # Subject
        'subject_overdue': '⚠️ WARNING — {amount} overdue — {name} — {period}',
        'subject_critical': '⚠️ WARNING — {count} critical issue(s) — {name}',
        'subject_default': '⚠️ Sales Warning — {name} — {period}',
        # Sections
        'ar_section': '📊 AR Outstanding & Aging',
        'total_outstanding_label': 'Total Outstanding',
        'overdue_label': 'Overdue',
        'customers_section': '🏢 Customers at Risk',
        'invoice_singular': 'invoice',
        'invoices_plural': 'invoices',
        'd_overdue': 'd overdue',
        # Alert category headers
        'backlog_section': '📦 Backlog Past ETD — Overdue Delivery',
        'kpi_section': '🎯 KPI Performance — Behind Target',
        'payment_section': '⏰ Payment Coming Due (Next 7 Days)',
        'ar_alerts_section': '💰 AR Overdue Alerts',
        # Table headers
        'th_aging': 'Aging', 'th_amount': 'Amount',
        'th_invoices': 'Invoices', 'th_share': 'Share',
        # Consequences
        'consequences_title': '⚠️ Consequences if not resolved within {days} days:',
        'consequences': [
            ('🚫', 'Credit terms with flagged customers will be suspended'),
            ('🚫', 'New Order Confirmation (OC) creation will be blocked for flagged customers'),
            ('🚫', 'Pending shipments may be held until payment is collected'),
        ],
        'action_line': (
            'Please contact the customer(s) immediately and update payment status.<br>'
            'Reply to this email with your action plan.'
        ),
        # CTA
        'btn_dashboard': '📊 Open Dashboard',
        'btn_payment': '💰 Payment', 'btn_backlog': '📦 Backlog', 'btn_kpi': '🎯 KPI',
        # Footer
        'footer_auto': '⚠️ This is an automated warning',
        'footer_from': 'from Prostech BI Dashboard',
        'footer_triggered': 'Triggered by {name}',
        'footer_manage': 'To manage notifications: Dashboard → 📧 Notifications tab',
        'footer_excel': '📎 Detailed data attached as Excel file.',
    },
    'vi': {
        'warning_title': '⚠️ Cảnh Báo Hiệu Suất Bán Hàng — Cần Hành Động Ngay',
        'subject_overdue': '⚠️ CẢNH BÁO — {amount} quá hạn — {name} — {period}',
        'subject_critical': '⚠️ CẢNH BÁO — {count} vấn đề nghiêm trọng — {name}',
        'subject_default': '⚠️ Cảnh Báo Bán Hàng — {name} — {period}',
        'ar_section': '📊 Công Nợ Phải Thu & Tuổi Nợ',
        'total_outstanding_label': 'Tổng Công Nợ',
        'overdue_label': 'Quá Hạn',
        'customers_section': '🏢 Khách Hàng Có Rủi Ro',
        'invoice_singular': 'hóa đơn',
        'invoices_plural': 'hóa đơn',
        'd_overdue': 'ngày quá hạn',
        'backlog_section': '📦 Đơn Hàng Quá Hạn Giao (Past ETD)',
        'kpi_section': '🎯 Hiệu Suất KPI — Chậm Tiến Độ',
        'payment_section': '⏰ Thanh Toán Sắp Đến Hạn (7 Ngày Tới)',
        'ar_alerts_section': '💰 Cảnh Báo Công Nợ Quá Hạn',
        'th_aging': 'Tuổi Nợ', 'th_amount': 'Số Tiền',
        'th_invoices': 'Hóa Đơn', 'th_share': 'Tỷ Lệ',
        'consequences_title': '⚠️ Hậu quả nếu không giải quyết trong {days} ngày:',
        'consequences': [
            ('🚫', 'Điều khoản tín dụng với khách hàng bị đánh dấu sẽ bị đình chỉ'),
            ('🚫', 'Việc tạo Xác Nhận Đơn Hàng (OC) mới sẽ bị chặn đối với khách hàng bị đánh dấu'),
            ('🚫', 'Các lô hàng đang chờ có thể bị giữ lại cho đến khi thu được thanh toán'),
        ],
        'action_line': (
            'Vui lòng liên hệ khách hàng ngay lập tức và cập nhật tình trạng thanh toán.<br>'
            'Trả lời email này kèm kế hoạch hành động của bạn.'
        ),
        'btn_dashboard': '📊 Mở Dashboard',
        'btn_payment': '💰 Thanh Toán', 'btn_backlog': '📦 Backlog', 'btn_kpi': '🎯 KPI',
        'footer_auto': '⚠️ Đây là cảnh báo tự động',
        'footer_from': 'từ Prostech BI Dashboard',
        'footer_triggered': 'Được gửi bởi {name}',
        'footer_manage': 'Quản lý thông báo: Dashboard → 📧 Tab Thông Báo',
        'footer_excel': '📎 Dữ liệu chi tiết được đính kèm dưới dạng file Excel.',
    },
}


def _t(lang: str, key: str, **kwargs) -> str:
    """Get translated text. Falls back to English if key not found."""
    texts = _TEXTS.get(lang, _TEXTS['en'])
    val = texts.get(key, _TEXTS['en'].get(key, key))
    if kwargs and isinstance(val, str):
        return val.format(**kwargs)
    return val


# =============================================================================
# BUILD WARNING EMAIL (v3.0)
# =============================================================================

def build_warning_email(
    warning_data: Dict,
    active_filters: Dict,
    sender_name: str = "Prostech BI",
    dashboard_url: str = "",
    cc_note: str = "",
    consequences: Optional[List[tuple]] = None,
    deadline_days: int = DEFAULT_DEADLINE_DAYS,
    lang: str = 'en',
    has_attachment: bool = False,
) -> tuple:
    """
    Build formal warning HTML email with AR detail and consequences.

    v3.0: Bilingual (en/vi), categorized alert sections, no more "Other Alerts".

    Args:
        warning_data:    Output of collect_warning_data()
        active_filters:  Current filter state
        sender_name:     Name of the person triggering the email
        dashboard_url:   Link to dashboard
        cc_note:         Note for CC recipients
        consequences:    Custom consequences list. None = use lang defaults.
        deadline_days:   Days before consequences take effect
        lang:            'en' or 'vi'

    Returns:
        Tuple of (subject: str, html_body: str)
    """
    bulletin = warning_data.get('bulletin', {})
    metrics = warning_data.get('metrics', {})
    ar_summary = warning_data.get('ar_summary', {})
    customers_at_risk = warning_data.get('customers_at_risk', [])

    employee_name = bulletin.get('employee_name', '')
    period_label = bulletin.get('period_label', '')
    alerts = bulletin.get('alerts', [])
    alert_count = bulletin.get('alert_count', 0)
    has_critical = bulletin.get('has_critical', False)

    total_overdue = ar_summary.get('total_overdue', 0)
    aging_table = ar_summary.get('aging_table', [])

    # Resolve consequences (use lang defaults if not provided)
    if consequences is None:
        consequences = _t(lang, 'consequences')

    S = _WARNING_STYLES

    # ─── Subject line ───
    if total_overdue > 0:
        subject = _t(lang, 'subject_overdue', amount=_fmt(total_overdue),
                      name=employee_name, period=period_label)
    elif has_critical:
        subject = _t(lang, 'subject_critical', count=alert_count, name=employee_name)
    else:
        subject = _t(lang, 'subject_default', name=employee_name, period=period_label)

    # ─── HTML Build ───
    parts = []

    # Header
    parts.append(f"""
    <div style="{S['container']}">
        <div style="{S['header']}">
            <h1 style="{S['header_title']}">{_t(lang, 'warning_title')}</h1>
            <p style="{S['header_sub']}">{_esc(employee_name)} &nbsp;|&nbsp; {_esc(period_label)} &nbsp;|&nbsp; {datetime.now().strftime('%d %b %Y, %H:%M')}</p>
        </div>
        <div style="{S['body']}">
    """)

    # CC note
    if cc_note:
        parts.append(f'<p style="font-size:12px;color:#666;font-style:italic;margin:0 0 16px 0;">{_esc(cc_note)}</p>')

    # ─── SECTION 1: AR OUTSTANDING & AGING ───
    if aging_table:
        total_outstanding = ar_summary.get('total_outstanding', 0)
        parts.append(f'<p style="{S["section_title"]}">{_t(lang, "ar_section")}</p>')
        parts.append(
            f'<p style="font-size:14px;color:#333;margin:0 0 10px 0;">'
            f'{_t(lang, "total_outstanding_label")}: <strong>{_fmt(total_outstanding)}</strong> '
            f'&nbsp;|&nbsp; {_t(lang, "overdue_label")}: '
            f'<strong style="color:#dc2626;">{_fmt(total_overdue)}</strong></p>'
        )

        # Aging table
        parts.append(f'<table style="{S["table"]}">')
        parts.append(
            f'<tr><th style="{S["th"]}">{_t(lang, "th_aging")}</th>'
            f'<th style="{S["th"]}">{_t(lang, "th_amount")}</th>'
            f'<th style="{S["th"]}">{_t(lang, "th_invoices")}</th>'
            f'<th style="{S["th"]}">{_t(lang, "th_share")}</th></tr>'
        )
        for row in aging_table:
            parts.append(
                f'<tr><td style="{S["td"]}">{row["icon"]} {_esc(row["bucket"])}</td>'
                f'<td style="{S["td_amount"]}">{_fmt(row["amount"])}</td>'
                f'<td style="{S["td"]}" align="center">{row["count"]}</td>'
                f'<td style="{S["td"]}" align="center">{row["share"]:.0%}</td></tr>'
            )
        parts.append('</table>')

    # ─── SECTION 2: CUSTOMERS AT RISK ───
    if customers_at_risk:
        inv_word = _t(lang, 'invoices_plural')
        d_overdue = _t(lang, 'd_overdue')
        parts.append(f'<p style="{S["section_title"]}">{_t(lang, "customers_section")}</p>')

        for cust in customers_at_risk:
            is_critical = cust['max_days_overdue'] >= 90
            box_style = S['customer_critical'] if is_critical else S['customer_box']
            icon = '🔴' if is_critical else '🟠'
            inv_count = cust['invoice_count']

            parts.append(f'<div style="{box_style}">')
            parts.append(
                f'<p style="margin:0;font-size:14px;font-weight:600;color:#333;">'
                f'{icon} {_esc(cust["customer"])} — {_fmt(cust["outstanding"])} '
                f'({inv_count} {inv_word}, {cust["max_days_overdue"]}{d_overdue})</p>'
            )
            if cust['invoices']:
                inv_list = ', '.join(cust['invoices'][:5])
                more = f" + {len(cust['invoices'])-5} more" if len(cust['invoices']) > 5 else ""
                parts.append(f'<p style="{S["invoice_list"]}">Invoices: {_esc(inv_list)}{more}</p>')
            parts.append('</div>')

    # ─── SECTION 3+: CATEGORIZED ALERTS (replaces "Other Alerts") ───
    _category_config = [
        ('backlog',          'backlog_section',    S['alert_box_backlog']),
        ('kpi',              'kpi_section',         S['alert_box_kpi']),
        ('payment_coming_due', 'payment_section',   S['alert_box_payment']),
        ('ar',               'ar_alerts_section',   S['alert_box']),
    ]

    for cat_key, title_key, box_style in _category_config:
        cat_alerts = [a for a in alerts if a.get('category') == cat_key]
        # Skip AR alerts section if we already showed the AR aging table
        if cat_key == 'ar' and aging_table:
            continue
        if not cat_alerts:
            continue

        parts.append(f'<p style="{S["section_title"]}">{_t(lang, title_key)}</p>')
        for a in cat_alerts:
            icon = a.get('icon', '•')
            parts.append(
                f'<div style="{box_style}">'
                f'<p style="margin:0;font-size:14px;color:#333;">{icon} {_esc(a["message"])}</p>'
                f'</div>'
            )

    # ─── CONSEQUENCES BLOCK ───
    parts.append(f'<div style="{S["consequences_box"]}">')
    parts.append(
        f'<p style="{S["consequences_title"]}">'
        f'{_t(lang, "consequences_title", days=deadline_days)}</p>'
    )
    for icon, text in consequences:
        parts.append(f'<p style="{S["consequences_item"]}">{icon} {_esc(text)}</p>')
    parts.append(
        f'<p style="margin:12px 0 0 0;font-size:14px;color:#991b1b;font-weight:600;">'
        f'{_t(lang, "action_line")}</p>'
    )
    parts.append('</div>')

    # ─── CTA BUTTONS ───
    if dashboard_url:
        page_url = f"{dashboard_url.rstrip('/')}/Salesperson_Performance"
        parts.append(f"""
            <div style="text-align:center;margin:24px 0 12px 0;">
                <a href="{_esc(page_url)}" style="{S['btn_primary']}">{_t(lang, 'btn_dashboard')}</a>
            </div>
            <div style="text-align:center;margin:0 0 8px 0;">
                <a href="{_esc(page_url)}" style="{S['btn_secondary']};margin:0 4px;">{_t(lang, 'btn_payment')}</a>
                <a href="{_esc(page_url)}" style="{S['btn_secondary']};margin:0 4px;">{_t(lang, 'btn_backlog')}</a>
                <a href="{_esc(page_url)}" style="{S['btn_secondary']};margin:0 4px;">{_t(lang, 'btn_kpi')}</a>
            </div>
        """)

    # Close body
    parts.append('</div>')

    # Footer
    triggered = (
        f'&nbsp;|&nbsp; {_t(lang, "footer_triggered", name=_esc(sender_name))}'
        if sender_name != 'Prostech BI' else ''
    )
    parts.append(f"""
        <div style="{S['footer']}">
            <p style="margin:0 0 4px 0;">
                <strong>{_t(lang, 'footer_auto')}</strong> {_t(lang, 'footer_from')}
                {triggered}
            </p>
            {'<p style="margin:0 0 4px 0;">' + _t(lang, 'footer_excel') + '</p>' if has_attachment else ''}
            <p style="margin:0;">{_t(lang, 'footer_manage')}</p>
        </div>
    </div>
    """)

    return subject, "\n".join(parts)


def build_warning_plain_text(
    warning_data: Dict,
    deadline_days: int = DEFAULT_DEADLINE_DAYS,
    lang: str = 'en',
) -> str:
    """Plain text version of warning email (bilingual)."""
    bulletin = warning_data.get('bulletin', {})
    ar_summary = warning_data.get('ar_summary', {})
    customers_at_risk = warning_data.get('customers_at_risk', [])
    alerts = bulletin.get('alerts', [])

    lines = [
        _t(lang, 'warning_title').replace('⚠️ ', ''),
        f"{bulletin.get('employee_name', '')} | {bulletin.get('period_label', '')}",
        "",
    ]

    # AR summary
    total_os = ar_summary.get('total_outstanding', 0)
    total_od = ar_summary.get('total_overdue', 0)
    if total_os > 0:
        lines.append(
            f"{_t(lang, 'total_outstanding_label')}: {_fmt(total_os)} | "
            f"{_t(lang, 'overdue_label')}: {_fmt(total_od)}"
        )
        for row in ar_summary.get('aging_table', []):
            lines.append(f"  {row['icon']} {row['bucket']}: {_fmt(row['amount'])} ({row['count']} inv)")
        lines.append("")

    # Customers
    if customers_at_risk:
        lines.append(f"{_t(lang, 'customers_section').replace('🏢 ', '')}:")
        for cust in customers_at_risk[:5]:
            lines.append(
                f"  • {cust['customer']} — {_fmt(cust['outstanding'])} "
                f"({cust['max_days_overdue']}{_t(lang, 'd_overdue')})"
            )
        lines.append("")

    # Categorized alerts
    _cat_labels = {
        'backlog': _t(lang, 'backlog_section'),
        'kpi': _t(lang, 'kpi_section'),
        'payment_coming_due': _t(lang, 'payment_section'),
    }
    for cat_key, label in _cat_labels.items():
        cat_alerts = [a for a in alerts if a.get('category') == cat_key]
        if cat_alerts:
            lines.append(f"{label}:")
            for a in cat_alerts:
                lines.append(f"  {a.get('icon', '•')} {a['message']}")
            lines.append("")

    # Consequences
    consequences = _t(lang, 'consequences')
    lines.append(_t(lang, 'consequences_title', days=deadline_days).replace('⚠️ ', ''))
    for icon, text in consequences:
        lines.append(f"  {icon} {text}")

    lines.extend([
        "",
        _t(lang, 'action_line').replace('<br>', '\n'),
        "—",
        f"Prostech BI Dashboard ({_t(lang, 'footer_auto').replace('⚠️ ', '')})",
    ])
    return "\n".join(lines)