# utils/salesperson_performance/notification/email_builder.py
"""
HTML Email Builder for Salesperson Performance Alerts.

Converts the warning bulletin (generated by warning_bulletin.py) into
a professional, responsive HTML email.

Phase 1: Team-level bulletin (same content as UI).
Phase 2 (future): Per-salesperson with individual KPIs.

Usage:
    from utils.salesperson_performance.notification.email_builder import (
        build_bulletin_email,
    )

    subject, html = build_bulletin_email(
        bulletin=warning_bulletin,
        active_filters=active_filters,
        overview_metrics=overview_metrics,
        sender_name="Quy Ngo",
    )

VERSION: 1.0.0
"""

import logging
from datetime import date, datetime
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


# =============================================================================
# CSS (inline — email clients strip <style> blocks)
# =============================================================================

_STYLES = {
    "container": (
        "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, "
        "Helvetica, Arial, sans-serif; max-width: 680px; margin: 0 auto; "
        "background: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; "
        "overflow: hidden;"
    ),
    "header": (
        "background: linear-gradient(135deg, #1f77b4, #2ca02c); color: #ffffff; "
        "padding: 20px 24px; font-size: 14px;"
    ),
    "header_title": "margin: 0 0 4px 0; font-size: 20px; font-weight: 700;",
    "header_sub": "margin: 0; font-size: 13px; opacity: 0.9;",
    "body": "padding: 20px 24px;",
    "headline": (
        "background: #f8f9fa; border-left: 4px solid #1f77b4; "
        "padding: 12px 16px; margin: 0 0 20px 0; font-size: 14px; "
        "color: #333; border-radius: 0 4px 4px 0; line-height: 1.5;"
    ),
    "section_title": (
        "font-size: 15px; font-weight: 600; margin: 20px 0 8px 0; "
        "color: #333;"
    ),
    # Severity boxes
    "box_high": (
        "background: #fef2f2; border-left: 4px solid #dc3545; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_medium": (
        "background: #fffbeb; border-left: 4px solid #f59e0b; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_low": (
        "background: #eff6ff; border-left: 4px solid #3b82f6; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "box_ok": (
        "background: #f0fdf4; border-left: 4px solid #22c55e; "
        "padding: 12px 16px; margin: 0 0 12px 0; border-radius: 0 4px 4px 0;"
    ),
    "alert_item": "margin: 4px 0; font-size: 13px; color: #333; line-height: 1.5;",
    "footer": (
        "background: #f8f9fa; padding: 16px 24px; font-size: 11px; "
        "color: #888; border-top: 1px solid #e0e0e0;"
    ),
    "btn": (
        "display: inline-block; padding: 8px 20px; background: #1f77b4; "
        "color: #ffffff; text-decoration: none; border-radius: 4px; "
        "font-size: 13px; font-weight: 600;"
    ),
    "muted": "color: #999; font-size: 12px;",
}


# =============================================================================
# PUBLIC API
# =============================================================================

def build_bulletin_email(
    bulletin: Dict,
    active_filters: Dict,
    overview_metrics: Optional[Dict] = None,
    sender_name: str = "Prostech BI",
    dashboard_url: str = "",
    cc_note: str = "",
) -> tuple:
    """
    Build HTML email from warning bulletin data.

    Args:
        bulletin:         Output of generate_warning_bulletin()
        active_filters:   Current filter state (period, year, dates)
        overview_metrics: Overview metrics dict (optional — for KPI snapshot)
        sender_name:      Name of the person triggering the email
        dashboard_url:    Link to dashboard (from APP_BASE_URL)
        cc_note:          Note for CC recipients (e.g., "Sent to your direct report X")

    Returns:
        Tuple of (subject: str, html_body: str)
    """
    period_label = bulletin.get("period_label", "")
    headline = bulletin.get("headline", "")
    alerts = bulletin.get("alerts", [])
    alert_count = bulletin.get("alert_count", 0)
    has_critical = bulletin.get("has_critical", False)

    # Subject line
    if has_critical:
        subject = f"🚨 Sales Alert — {alert_count} issue(s) — {period_label}"
    elif alert_count > 0:
        subject = f"⚡ Sales Bulletin — {alert_count} item(s) — {period_label}"
    else:
        subject = f"✅ Sales Bulletin — All Clear — {period_label}"

    # Build HTML
    html_parts = []

    # --- Header ---
    html_parts.append(f"""
    <div style="{_STYLES['container']}">
        <div style="{_STYLES['header']}">
            <h1 style="{_STYLES['header_title']}">⚡ Sales Performance Bulletin</h1>
            <p style="{_STYLES['header_sub']}">{period_label} &nbsp;|&nbsp; Generated {datetime.now().strftime('%d %b %Y, %H:%M')}</p>
        </div>
        <div style="{_STYLES['body']}">
    """)

    # --- CC Note (for managers) ---
    if cc_note:
        html_parts.append(f"""
            <p style="font-size: 12px; color: #666; font-style: italic; margin: 0 0 16px 0;">
                {_esc(cc_note)}
            </p>
        """)

    # --- Headline ---
    html_parts.append(f"""
        <div style="{_STYLES['headline']}">
            <strong>📊 Snapshot:</strong> {_esc(headline)}
        </div>
    """)

    # --- KPI Snapshot (optional) ---
    if overview_metrics:
        html_parts.append(_build_kpi_snapshot(overview_metrics))

    # --- Alerts ---
    if alerts:
        sorted_alerts = sorted(
            alerts,
            key=lambda a: {"high": 0, "medium": 1, "low": 2}.get(a["severity"], 9),
        )
        high = [a for a in sorted_alerts if a["severity"] == "high"]
        medium = [a for a in sorted_alerts if a["severity"] == "medium"]
        low = [a for a in sorted_alerts if a["severity"] == "low"]

        if high:
            html_parts.append(_build_alert_section(
                title="🚨 Action Required",
                alerts=high,
                box_style=_STYLES["box_high"],
            ))

        if medium:
            html_parts.append(_build_alert_section(
                title="⚠️ Monitor",
                alerts=medium,
                box_style=_STYLES["box_medium"],
            ))

        if low:
            html_parts.append(_build_alert_section(
                title="ℹ️ For Your Awareness",
                alerts=low,
                box_style=_STYLES["box_low"],
            ))
    else:
        html_parts.append(f"""
            <div style="{_STYLES['box_ok']}">
                <p style="{_STYLES['alert_item']}">
                    ✅ <strong>No issues detected</strong> — all metrics within normal range.
                </p>
            </div>
        """)

    # --- CTA Button ---
    if dashboard_url:
        html_parts.append(f"""
            <div style="text-align: center; margin: 24px 0 8px 0;">
                <a href="{_esc(dashboard_url)}" style="{_STYLES['btn']}">
                    View Dashboard →
                </a>
            </div>
        """)

    # --- Close body ---
    html_parts.append("</div>")

    # --- Footer ---
    html_parts.append(f"""
        <div style="{_STYLES['footer']}">
            <p style="margin: 0 0 4px 0;">
                Auto-generated by <strong>Prostech BI Dashboard</strong>
                {f'&nbsp;|&nbsp; Triggered by {_esc(sender_name)}' if sender_name != 'Prostech BI' else ''}
            </p>
            <p style="margin: 0;">
                To manage notifications: Dashboard → Setup → Notifications
            </p>
        </div>
    </div>
    """)

    html_body = "\n".join(html_parts)
    return subject, html_body


def build_bulletin_plain_text(bulletin: Dict) -> str:
    """
    Build plain text fallback from bulletin.

    Simple text version for email clients that don't render HTML.
    """
    lines = [
        f"Sales Performance Bulletin — {bulletin.get('period_label', '')}",
        "",
        f"Snapshot: {bulletin.get('headline', '')}",
        "",
    ]

    alerts = bulletin.get("alerts", [])
    if alerts:
        for a in alerts:
            severity_map = {"high": "🔴", "medium": "🟡", "low": "🔵"}
            icon = severity_map.get(a["severity"], "•")
            lines.append(f"  {icon} {a['message']}")
    else:
        lines.append("  ✅ No issues detected.")

    lines.extend([
        "",
        "—",
        "Auto-generated by Prostech BI Dashboard",
    ])

    return "\n".join(lines)


# =============================================================================
# INTERNAL HELPERS
# =============================================================================

def _esc(text: str) -> str:
    """Escape HTML entities."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _fmt(value: float) -> str:
    """Format currency: $1.2M / $850K / $1,234"""
    if abs(value) >= 1_000_000:
        return f"${value / 1_000_000:,.1f}M"
    elif abs(value) >= 10_000:
        return f"${value / 1_000:,.0f}K"
    else:
        return f"${value:,.0f}"


def _build_kpi_snapshot(metrics: Dict) -> str:
    """Build KPI summary table from overview_metrics."""
    revenue = metrics.get("total_revenue", 0)
    gp = metrics.get("total_gp", 0)
    gp_pct = metrics.get("gp_percent", 0)
    gp1 = metrics.get("total_gp1", 0)
    invoices = metrics.get("total_invoices", 0)
    customers = metrics.get("total_customers", 0)

    row_style = "padding: 6px 12px; font-size: 13px; border-bottom: 1px solid #eee;"
    label_style = f"{row_style} color: #666; width: 120px;"
    value_style = f"{row_style} font-weight: 600; color: #333;"

    return f"""
    <table style="width: 100%; border-collapse: collapse; margin: 0 0 16px 0;">
        <tr>
            <td style="{label_style}">💰 Revenue</td>
            <td style="{value_style}">{_fmt(revenue)}</td>
            <td style="{label_style}">📈 GP</td>
            <td style="{value_style}">{_fmt(gp)} ({gp_pct:.1f}%)</td>
        </tr>
        <tr>
            <td style="{label_style}">📊 GP1</td>
            <td style="{value_style}">{_fmt(gp1)}</td>
            <td style="{label_style}">📋 Invoices</td>
            <td style="{value_style}">{invoices:,}</td>
        </tr>
    </table>
    """


def _build_alert_section(
    title: str,
    alerts: List[Dict],
    box_style: str,
) -> str:
    """Build one alert severity section."""
    items_html = "\n".join(
        f'<p style="{_STYLES["alert_item"]}">{a.get("icon", "•")} {_esc(a["message"])}</p>'
        for a in alerts
    )

    return f"""
        <p style="{_STYLES['section_title']}">{title}</p>
        <div style="{box_style}">
            {items_html}
        </div>
    """
